config/routes.rb
Rails.application.routes.draw do
  root to: "backoffice#index"
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/admin", to: "backoffice#index"

  namespace :backoffice do
    resources :users, except: :show
    resources :projects
    resource :session, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::ActiveStorage

  attr_accessor :data

  has_one_attached :storage_data
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_content
    rails_representation_url(storage_data.variant(resize: '800>').processed, only_path: true)
  end

  def url_thumb
    rails_representation_url(storage_data.variant(resize: '118x100').processed, only_path: true)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :cover

  validates_presence_of :order, :name, :description, :cover, :template
  validates_uniqueness_of :order, if: -> { self.order.present? }
  validates :order, numericality: { greater_than: 0 }, if: -> { self.order.present? }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_uniqueness_of :email
  validates_confirmation_of :password, on: :create
  validates_presence_of :name, :email
  validates_presence_of :password_confirmation, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backoffice/projects_controller.rb
class Backoffice::ProjectsController < BackofficeController
  before_action :set_project, only: [:edit, :update, :destroy, :show]

  def index
    @projects = Project.order(:order)
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to backoffice_projects_path, notice: "Projeto criado com sucesso."
    else
      render :new
    end
  
  end
  
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit  
  end
  
  def update
    if @project.update(project_params)
      redirect_to backoffice_projects_path, notice: "Projeto atualizado com sucesso."
    else
      render :edit
    end
  end
  
  def destroy
    @project.destroy
    redirect_to backoffice_projects_path, notice: "Usuário excluído com sucesso."
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:order, :name, :description, :active, :cover, :template)
  end
end

app/controllers/backoffice/sessions_controller.rb
class Backoffice::SessionsController < BackofficeController
  skip_before_action :authenticate

  def new
    redirect_to admin_path if logged_in?
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_path    
    else
      flash.alert = "E-mail ou Senha incorretos."
      redirect_to new_backoffice_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_backoffice_session_path
  end
end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < BackofficeController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order(:name)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to backoffice_users_path, notice: "Usuário criado com sucesso."
    else
      render :new
    end
  
  end
  
  def edit  
  end
  
  def update
    if @user.update(user_params)
      redirect_to backoffice_users_path, notice: "Usuário atualizado com sucesso."
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to backoffice_users_path, notice: "Usuário excluído com sucesso."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :active)
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  layout 'backoffice'

  before_action :authenticate

  def index
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
    redirect_to new_backoffice_session_path
  end
  helper_method :current_user

  def logged_in?
    current_user.present?
  end
  helper_method :logged_in?

  def authenticate
    redirect_to new_backoffice_session_path unless logged_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/file_uploads_helper.rb
module Backoffice::FileUploadsHelper
end

app/helpers/backoffice/projects_helper.rb
module Backoffice::ProjectsHelper
  def link_to_preview_project_cover(project)
    if project.cover.attached?
      url_for(project.cover)
    else
      ""
    end
  end
end

app/helpers/backoffice/session_helper.rb
module Backoffice::SessionHelper
end

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
  def boolean_label(item)
    if item
      "<span class='badge badge-success'>Sim</span>".html_safe
    else
      "<span class='badge badge-danger'>Não</span>".html_safe
    end
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def nav_link_to(body, url, controller_name, icon = nil, html_options = {})
      active = "active" if current_section?(controller_name)
      content_tag :li, class: [active, 'nav-item'] do
        link_to url, html_options.merge(class: 'nav-link') do
          "#{content_tag(:span, '', class: "fa fa-#{icon}")} #{body}".html_safe
        end
      end
    end

    def nav_dropdown_item(body, url, icon, html_options = {})
      link_to url, html_options.merge(class: 'dropdown-item') do
        "#{content_tag(:span, '', class: "fa fa-#{icon}")} #{body}".html_safe
      end
    end

    def current_section?(section)
      if section.is_a? Array
        section.each do |s|
          return true if request.path.split('/').include?(s)
        end
      else
        request.path.split('/').include?(section)
      end
  end
end

app/views/backoffice/index.html.erb
<h1>Bem vindo ao Index</h1>

app/views/backoffice/projects/_form.html.erb
<%= form_for [:backoffice, @project] do |f| %>
  <%= render  "layouts/backoffice_shared/errors_message", resource: @project %>

  <div class="form-row">
    <div class="form-group col-md-2">
      <%= f.label :ordem %>
      <%= f.number_field :order, class:"form-control" %>
    </div>

    <div class="form-group col-md-10">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-2">
      <%= f.label :cover %>
      <%= f.file_field :cover, direct_upload: true %>
    </div>

    <div class="form-group col-md-2">
      <%= image_tag link_to_preview_project_cover(@project), id:'image' %>
    </div>
  </div>

  <div class="custom-control custom-switch">
    <div class="form-group">
      <%= f.check_box :active, class: "custom-control-input" %>
      <%= f.label :active, class: "custom-control-label" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= f.label :template %>
      <%= f.cktext_area :template, ckeditor: { language: 'pt-BR' } %>
    </div>
  </div>

  <div class="text-right">
    <%= link_to  "Voltar", backoffice_projects_path, class: "btn btn-dark" %>
    <%= f.submit 'Salvar', class: "btn btn-primary" %>
  </div>
<% end %>
<br>

app/views/backoffice/projects/_header.html.erb
<% index = true if params[:action] == 'index' %>
<h5 class="header">
  <%= fa_icon 'copy'%> Projetos

  <%= link_to add_path, class: 'icon-link' do %>
    <%= fa_icon "plus-circle" %>
  <% end if index %>

  <%= "- #{action}" unless index %>
</h5>

<% unless index %>
  <hr>
<% end %>

app/views/backoffice/projects/_template.html.erb
<%= @project.template.html_safe %>

app/views/backoffice/projects/edit.html.erb
<div class="container">
  <%= render "header", action: "Editar" %>
  <%= render  "form" %>
</div>

app/views/backoffice/projects/index.html.erb
<div class="container">
  <%= render "header", add_path: new_backoffice_project_path %>
      
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Ordem</th>
        <th scope="col">Nome</th>
        <th scope="col">Ativo</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% if @projects.each do |project| %>
        <tr>
          <td><%= project.order %></td>
          <td><%= project.name %></td>
          <td><%= boolean_label(project.active?) %></td>

          <td class="table-actions">
            <%= link_to backoffice_project_path(project), remote: true, class: 'icon-link upload-icon-link', data: { toggle: 'tooltip' }, title: "Visualizar Template" do %>
              <%= fa_icon "search-plus" %>
            <% end %>

            <%= link_to edit_backoffice_project_path(project), class: 'icon-link', data: { toggle: 'tooltip' }, title: "Editar" do %>
              <%= fa_icon "edit" %>
            <% end %>

            <%= link_to backoffice_project_path(project), class: 'icon-link remove-icon-link', method: :delete, data: { confirm: 'Você tem certeza?', toggle: 'tooltip'}, title: "Excluir" do %>
              <%= fa_icon "trash" %>
            <% end %>
          </td>
        </tr>       
      <% end.empty? %>
        <tr>
          <td colspan='4'>Nenhum projeto cadastrado.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/backoffice/projects/new.html.erb
<div class="container">
  <%= render "header", action: "Adicionar" %>
  <%= render  "form" %>
</div>
  

app/views/backoffice/projects/show.js.erb
$("#modal-window").find(".modal-title").html("Visualizando - <%= j @project.name %>");
$("#modal-window").find(".modal-body").html("<%= j (render 'template') %>");
$("#modal-window").modal();

app/views/backoffice/users/_form.html.erb
<%= form_for [:backoffice, @user] do |f| %>
  <%= render  "layouts/backoffice_shared/errors_message", resource: @user %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :email %>
      <%= f.email_field :email, class:"form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :password %>
      <%= f.password_field :password, class:"form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class:"form-control" %>
    </div>
  </div>
  
  <div class="custom-control custom-switch">
    <div class="form-group">
      <%= f.check_box :admin, class: "custom-control-input" %>
      <%= f.label :admin, class: "custom-control-label" %>
    </div>

    <div class="form-group">
      <%= f.check_box :active, class: "custom-control-input" %>
      <%= f.label :active, class: "custom-control-label" %>
    </div>
  </div> 

  <div class="text-right">
    <%= link_to  "Voltar", backoffice_users_path, class: "btn btn-dark" %>
    <%= f.submit 'Salvar', class: "btn btn-primary" %>
  </div>
  
<% end %>
<br>

app/views/backoffice/users/_header.html.erb
<% index = true if params[:action] == 'index' %>
<h5 class="header">
  <%= fa_icon 'users'%> Usuários

  <%= link_to add_path, class: 'icon-link' do %>
    <%= fa_icon "plus-circle" %>
  <% end if index %>

  <%= "- #{action}" unless index %>
</h5>

<% unless index %>
  <hr>
<% end %>

app/views/backoffice/users/edit.html.erb
<div class="container">
  <%= render "header", action: "Editar" %>
  <%= render  "form" %>
</div>

app/views/backoffice/users/index.html.erb
<div class="container">
  <%= render "header", add_path: new_backoffice_user_path %>

  <div class="table-responsive-md">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Nome</th>
          <th>E-mail</th>
          <th>Ativo</th>
          <th class="text-center">Administrador</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each_with_index do |user, index| %>
          <tr>
            <th><%= index + 1 %></th>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= boolean_label(user.active?) %></td>
            <td class="text-center"><%= boolean_label(user.admin?) %></td>

            <td class="table-actions">
              <%= link_to edit_backoffice_user_path(user), class: 'icon-link' do %>
                <%= fa_icon "edit" %>
              <% end %>

              <%= link_to backoffice_user_path(user), class: 'icon-link remove-icon-link', method: :delete, data: { confirm: 'Você tem certeza?'} do %>
                <%= fa_icon "trash" %>
              <% end if current_user.admin? && user != current_user %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/backoffice/users/new.html.erb
<div class="container">
  <%= render "header", action: "Adicionar" %>
  <%= render  "form" %>
</div>
  

app/views/layouts/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="modal-window" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaCamila</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, user-scalable=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Admin</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render  "layouts/backoffice_shared/navigation" %>
      <%= render  "layouts/backoffice_shared/alerts" %>    
    <% end %>
    <%= yield %>
    <%= render  "layouts/modal" %>

  
  </body>
</html>

app/views/layouts/backoffice_shared/_alerts.html.erb
<% if alert.present? %>
  <div class="alert alert-danger alert-dismissible" fade show role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="oi oi-warning" aria-hidden="true"></span> <%= alert %>
  </div>
<% end %>

<% if notice.present? %>
  <div class="alert alert-info alert-dismissible" fade show role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="oi oi-info" aria-hidden="true"></span> <%= notice %>
  </div>
<% end %>

app/views/layouts/backoffice_shared/_errors_message.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h5>
      <span class="oi oi-danger" aria-hidden="true"></span> Problema(s) encontrado(s):
    </h5>
    <ul class="mb-0">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/backoffice_shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/admin">Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">      
      <%= nav_link_to "Início", admin_path, 'admin', 'home' %>
      <%= nav_link_to "Projetos", backoffice_projects_path, 'projects', 'copy' %>
      <%= nav_link_to "Combos", admin_path, 'packages', 'columns' %>
      <%= nav_link_to "Usuários", backoffice_users_path, 'users', 'users' %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <%= nav_link_to current_user.name.capitalize, edit_backoffice_user_path(current_user), 'users', 'user' %>

      <%= link_to backoffice_session_path, method: :delete, class: "nav-link" do %>
        <%= fa_icon "sign-out" %> Sair
      <% end %>
    </ul>
  </div>
</nav>